"use client";

import React, { useState, useEffect } from "react";
import { useAccount } from "@/contexts/AccountContext";
import { insforge } from "@/lib/insforge";
import { AlertOctagon, TrendingDown, BookX, Trash2 } from "lucide-react";
import { motion } from "framer-motion";

export default function MistakeLibraryPage() {
  const { activeAccount } = useAccount();
  const [mistakes, setMistakes] = useState<any[]>([]);
  const [trades, setTrades] = useState<any[]>([]);
  
  useEffect(() => {
    fetchData();
  }, [activeAccount]);

  const fetchData = async () => {
    if (!activeAccount) return;
    try {
      // For now, we will extract mistakes directly from the trades table
      // as they are generated by the AI and saved in the trades.mistakes array
      const { data: tradesData } = await insforge.database
        .from("trades")
        .select("id, pair, date, mistakes, profit")
        .eq("account_id", activeAccount.id);

      if (tradesData) {
        setTrades(tradesData);
        
        // Aggregate mistakes
        const mistakeMap = new Map();
        tradesData.forEach(trade => {
          if (trade.mistakes && Array.isArray(trade.mistakes)) {
            trade.mistakes.forEach(mistake => {
              if (mistake === "None detected") return;
              
              if (mistakeMap.has(mistake)) {
                const existing = mistakeMap.get(mistake);
                mistakeMap.set(mistake, {
                  name: mistake,
                  frequency: existing.frequency + 1,
                  totalLost: existing.totalLost + (trade.profit < 0 ? Math.abs(trade.profit) : 0),
                  lastOccurrence: trade.date
                });
              } else {
                mistakeMap.set(mistake, {
                  name: mistake,
                  frequency: 1,
                  totalLost: trade.profit < 0 ? Math.abs(trade.profit) : 0,
                  lastOccurrence: trade.date
                });
              }
            });
          }
        });
        
        setMistakes(Array.from(mistakeMap.values()).sort((a,b) => b.frequency - a.frequency));
      }
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="flex-1 p-6 lg:p-10 overflow-y-auto bg-black text-white space-y-10">
      <header>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Mistake Library</h1>
        <p className="text-gray-400">Identify and eliminate recurring errors draining your edge.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 lg:col-span-2">
          <div className="flex items-center gap-3 mb-6">
            <BookX className="text-rose-500 w-5 h-5" />
            <h2 className="text-lg font-bold">Aggregated Errors</h2>
          </div>
          
          <div className="space-y-4">
            {mistakes.length === 0 ? (
              <p className="text-sm text-white/40">No mistakes detected yet. AI logs mistakes from your journal automatically.</p>
            ) : (
              mistakes.map((mistake, idx) => (
                <div key={idx} className="bg-[#111] border border-white/5 rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div>
                    <h3 className="text-base font-bold text-white/90">{mistake.name}</h3>
                    <div className="flex gap-4 mt-2 text-xs text-white/40">
                      <span>Last seen: {mistake.lastOccurrence}</span>
                      <span className="text-rose-400 font-semibold">Total Cost: ${mistake.totalLost}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex flex-col items-center bg-black border border-white/5 rounded-lg px-4 py-2">
                      <span className="text-[10px] uppercase text-white/40 font-bold tracking-wider">Frequency</span>
                      <span className="text-xl font-bold text-rose-500">{mistake.frequency}</span>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="space-y-6">
          <div className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6">
            <h3 className="text-sm font-bold text-white/50 uppercase tracking-widest mb-4">Biggest Leak</h3>
            {mistakes.length > 0 ? (
              <div className="text-center p-6 border border-rose-500/20 bg-rose-500/5 rounded-xl">
                <AlertOctagon className="w-12 h-12 text-rose-500 mx-auto mb-4" />
                <h4 className="text-xl font-bold text-white/90 mb-1">{mistakes[0].name}</h4>
                <p className="text-xs text-rose-400 font-medium">Occurred {mistakes[0].frequency} times</p>
                <div className="mt-4 text-[10px] text-white/50">
                  Focus entirely on eliminating this mistake this week. It is costing you your edge.
                </div>
              </div>
            ) : (
              <div className="text-center text-sm text-white/40">No data available</div>
            )}
          </div>
          
          <div className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6">
            <h3 className="text-sm font-bold text-white/50 uppercase tracking-widest mb-4">Cost of Mistakes</h3>
            {mistakes.length > 0 ? (
              <div className="flex items-center gap-4">
                <TrendingDown className="w-8 h-8 text-rose-500" />
                <div>
                  <div className="text-2xl font-bold font-mono text-white/90">
                    ${mistakes.reduce((acc, curr) => acc + curr.totalLost, 0)}
                  </div>
                  <div className="text-[10px] text-white/40 uppercase tracking-widest">Total Capital Leaked</div>
                </div>
              </div>
            ) : (
              <div className="text-sm text-white/40">No data available</div>
            )}
          </div>
        </motion.div>

      </div>
    </div>
  );
}
