"use client";

import { motion } from "framer-motion";
import { AssessmentResults } from "@/lib/analyzerLogic";
import { PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip } from "recharts";
import { AlertTriangle, Brain, Target, Shield, TrendingUp, ChevronRight, CheckCircle2 } from "lucide-react";

interface AnalyzerResultsProps {
  results: AssessmentResults;
}

export function AnalyzerResults({ results }: AnalyzerResultsProps) {
  const radarData = [
    { subject: 'Psychology', score: results.scores.psychology, fullMark: 100 },
    { subject: 'Discipline', score: results.scores.discipline, fullMark: 100 },
    { subject: 'Risk Mgt', score: results.scores.risk, fullMark: 100 },
    { subject: 'Execution', score: results.scores.execution, fullMark: 100 },
    { subject: 'Stability', score: results.scores.stability, fullMark: 100 },
  ];

  const scoreCards = [
    { label: "Profitability Readiness", value: results.scores.profitabilityReadiness, icon: TrendingUp, highlight: true },
    { label: "Psychology & Emotion", value: results.scores.psychology, icon: Brain },
    { label: "Discipline & Patience", value: results.scores.discipline, icon: Target },
    { label: "Risk Management", value: results.scores.risk, icon: Shield },
  ];

  return (
    <div className="relative z-10 w-full min-h-screen flex flex-col items-center pt-24 pb-24 px-4 bg-white dark:bg-black transition-colors duration-300">
      
      {/* Dashboard Container */}
      <motion.div 
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="w-full max-w-[1200px] flex flex-col gap-8"
      >
        
        {/* Header */}
        <div className="flex flex-col items-center text-center gap-4 mb-8">
          <h1 className="text-3xl md:text-5xl font-bold text-black dark:text-white tracking-tight">
            Your Performance & Psychology Report
          </h1>
          <p className="text-gray-600 dark:text-gray-400 max-w-2xl text-sm md:text-base">
            Generated by TradeSide AI Coach based on your assessment answers. This report reveals the hidden psychological roadblocks preventing your consistency.
          </p>
        </div>

        {/* Top Grid: Scores and Radar */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Radar Chart Panel */}
          <div className="lg:col-span-1 bg-[#050505] border border-white/10 rounded-3xl p-6 shadow-2xl flex flex-col items-center justify-center min-h-[350px]">
            <h3 className="text-lg font-bold text-white self-start w-full mb-4">Attribute Radar</h3>
            <div className="w-full h-full flex-1 min-h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                  <PolarGrid stroke="rgba(255,255,255,0.1)" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: 'rgba(255,255,255,0.5)', fontSize: 12 }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                  <Radar
                    name="Your Profile"
                    dataKey="score"
                    stroke="#D4AF37"
                    fill="#D4AF37"
                    fillOpacity={0.4}
                  />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#000', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px' }}
                    itemStyle={{ color: '#D4AF37' }}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Scores Panel */}
          <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-6">
            {scoreCards.map((card, idx) => (
              <div 
                key={card.label}
                className={`flex flex-col justify-between p-6 rounded-3xl border ${card.highlight ? 'bg-[#D4AF37]/10 border-[#D4AF37]/30' : 'bg-[#050505] border-white/10'}`}
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className={`p-2 rounded-lg ${card.highlight ? 'bg-[#D4AF37]/20 text-[#D4AF37]' : 'bg-white/5 text-gray-400'}`}>
                    <card.icon className="w-5 h-5" />
                  </div>
                  <h4 className={`font-semibold ${card.highlight ? 'text-[#D4AF37]' : 'text-gray-300'}`}>{card.label}</h4>
                </div>
                <div className="flex items-end gap-2">
                  <span className={`text-5xl font-black ${card.highlight ? 'text-[#D4AF37]' : 'text-white'}`}>
                    {card.value}
                  </span>
                  <span className="text-gray-500 mb-1 font-medium">/ 100</span>
                </div>
                {/* Progress Bar under score */}
                <div className="w-full h-1.5 bg-white/5 rounded-full mt-4 overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${card.value}%` }}
                    transition={{ duration: 1, delay: 0.2 + (idx * 0.1) }}
                    className={`h-full ${card.highlight ? 'bg-[#D4AF37]' : 'bg-white'}`}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* AI Insight & Personality */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white/60 dark:bg-[#050505] border border-[#D4AF37]/20 rounded-3xl p-8 relative overflow-hidden backdrop-blur-md">
            <div className="absolute top-0 right-0 w-64 h-64 bg-[#D4AF37]/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none" />
            <h3 className="text-[#D4AF37] font-semibold mb-2 uppercase tracking-wide text-sm">Your Trader Personality</h3>
            <h2 className="text-3xl font-bold text-black dark:text-white mb-4">{results.personality.name}</h2>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed text-lg">{results.personality.description}</p>
          </div>

          <div className="bg-[#050505] border border-white/10 rounded-3xl p-8">
            <div className="flex items-center gap-2 mb-4">
              <Brain className="text-brand-orange w-5 h-5" />
              <h3 className="text-white font-semibold uppercase tracking-wide text-sm">AI Coach Insight</h3>
            </div>
            <p className="text-gray-400 leading-relaxed italic border-l-2 border-brand-orange/50 pl-4">
              "{results.aiInsight}"
            </p>
          </div>
        </div>

        {/* Root Causes */}
        <div className="bg-white/60 dark:bg-[#050505] border border-black/10 dark:border-white/10 rounded-3xl p-8 shadow-xl mt-4 backdrop-blur-md">
          <h3 className="text-2xl font-bold text-black dark:text-white mb-6">Top Roadblocks to Profitability</h3>
          <div className="flex flex-col gap-4">
            {results.rootCauses.map((cause, idx) => (
              <div key={idx} className="flex flex-col md:flex-row gap-4 md:items-start p-4 rounded-2xl bg-white/5 border border-white/5">
                <div className="flex-shrink-0 mt-1">
                  <AlertTriangle className={`w-6 h-6 ${cause.severity > 7 ? 'text-red-500' : 'text-yellow-500'}`} />
                </div>
                <div className="flex flex-col gap-1 flex-1">
                  <h4 className="text-white font-bold text-lg">{cause.title}</h4>
                  <p className="text-gray-400 text-sm">{cause.description}</p>
                </div>
                <div className="w-full md:w-1/3 bg-white/5 rounded-xl p-3 border border-white/5">
                  <span className="text-xs text-[#D4AF37] font-semibold uppercase block mb-1">Recommended Fix</span>
                  <p className="text-sm text-gray-300">{cause.fix}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 30-Day Action Plan */}
        <div className="bg-white/60 dark:bg-[#050505] border border-black/10 dark:border-white/10 rounded-3xl p-8 shadow-xl mt-4 backdrop-blur-md">
          <h3 className="text-2xl font-bold text-black dark:text-white mb-2">30-Day Action Plan</h3>
          <p className="text-gray-600 dark:text-gray-400 mb-8">Follow this week-by-week protocol to systematically eliminate your weaknesses.</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {Object.entries(results.actionPlan).map(([week, tasks], idx) => (
              <div key={week} className="flex flex-col bg-black rounded-2xl border border-white/10 p-5">
                <div className="inline-block px-3 py-1 bg-white/10 text-white text-xs font-bold uppercase rounded-full self-start mb-4">
                  Week {idx + 1}
                </div>
                <ul className="flex flex-col gap-3">
                  {tasks.map((task, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                      <CheckCircle2 className="w-4 h-4 text-[#D4AF37] flex-shrink-0 mt-0.5" />
                      <span>{task}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Lead Gen CTA */}
        <div className="w-full relative overflow-hidden rounded-3xl mt-8">
          <div className="absolute inset-0 bg-gradient-to-br from-[#D4AF37]/20 via-white dark:via-black to-[#ff7f11]/20 z-0" />
          <div className="absolute inset-0 bg-white/60 dark:bg-black/60 backdrop-blur-sm z-0" />
          <div className="absolute inset-[-100%] bg-[conic-gradient(from_90deg_at_50%_50%,transparent_0%,transparent_50%,#D4AF37_70%,#ffffff_100%)] animate-[spin_4s_linear_infinite] opacity-30 z-0" />
          
          <div className="relative z-10 flex flex-col items-center text-center p-12 md:p-16 border border-[#D4AF37]/30 rounded-3xl">
            <h2 className="text-3xl md:text-4xl font-bold text-black dark:text-white mb-4">Want a Professional Review?</h2>
            <p className="text-gray-700 dark:text-gray-300 max-w-2xl mb-8 text-lg">
              Stop guessing. Book a free consultation with a TradeSide performance coach to go over this exact report and map out your journey to consistent profitability.
            </p>
            <div className="flex flex-col sm:flex-row items-center gap-4">
              <button className="bg-[#D4AF37] text-black px-8 py-4 rounded-full font-bold hover:bg-white transition-colors shadow-[0_0_30px_rgba(212,175,55,0.4)]">
                Book Free Consultation
              </button>
              <button className="bg-white/10 text-white border border-white/20 px-8 py-4 rounded-full font-bold hover:bg-white/20 transition-colors">
                Download PDF Report
              </button>
            </div>
          </div>
        </div>

      </motion.div>
    </div>
  );
}
